ATSERVICES:
  - CASSANDRA:
      image: stratio/cassandra-lucene-index:%%VERSION
      sleep: 30
      volumes:
        - jts:1.14.0

ATPARAMETERS: >
    -Dit-embedded=false
    -Dit.host=%%CASSANDRA
    -DJACOCO_SERVER=%%CASSANDRA
    -DLOCAL_JMX=no



